# Generated by Django 4.2.5 on 2023-09-23 18:11

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=bookings.models.generate_unique_identifier, max_length=6, unique=True)),
            ],
        ),
    ]
