# Generated by Django 4.2.5 on 2023-09-23 19:33

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='method_of_payment',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='identifier',
            field=models.CharField(default=bookings.models.generate_unique_identifier, max_length=5, unique=True),
        ),
    ]
